// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDayFUBjvmHq1crjwyYYRFxYWY03db9hSQ',
    appId: '1:945261419738:web:275ddfeee0eeb9ac0619e3',
    messagingSenderId: '945261419738',
    projectId: 'barberbook-79470',
    authDomain: 'barberbook-79470.firebaseapp.com',
    storageBucket: 'barberbook-79470.appspot.com',
    measurementId: 'G-22GJXS4YTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2lqcH5a_17ZfKgG5qY9VNReKnos4TZE',
    appId: '1:945261419738:android:bfb93f45bb22a2880619e3',
    messagingSenderId: '945261419738',
    projectId: 'barberbook-79470',
    storageBucket: 'barberbook-79470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCqM4j-fzAiXNa7G_sjjAd-1IBKraeg0',
    appId: '1:945261419738:ios:d71b66496816929f0619e3',
    messagingSenderId: '945261419738',
    projectId: 'barberbook-79470',
    storageBucket: 'barberbook-79470.appspot.com',
    iosBundleId: 'com.example.barberbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCqM4j-fzAiXNa7G_sjjAd-1IBKraeg0',
    appId: '1:945261419738:ios:a6c50263d3aa68960619e3',
    messagingSenderId: '945261419738',
    projectId: 'barberbook-79470',
    storageBucket: 'barberbook-79470.appspot.com',
    iosBundleId: 'com.example.barberbook.RunnerTests',
  );
}
